/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vistas;

import Entidades.Producto;
import java.util.TreeSet;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author CCMEW
 */
public class ListaPrecio extends javax.swing.JInternalFrame {

    DefaultTableModel tablaProducto = new DefaultTableModel();

    private TreeSet<Producto> productos;
    private double buscar1;
    /**
     * Creates new form ListaPrecio
     */
    public ListaPrecio(TreeSet<Producto> productos) {
        
        initComponents();
        this.productos=productos;

       
        
        String[]titulo=new String[]{ "Código", "Descripcion", "Precio","Rubro", "Stock"};
        tablaProducto.setColumnIdentifiers(titulo);
        tablaProd.setModel(tablaProducto);
        mostrarTodo();
    }

  

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jtEntre1 = new javax.swing.JTextField();
        jtEntre2 = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaProd = new javax.swing.JTable();
        jLabel4 = new javax.swing.JLabel();

        setClosable(true);
        setResizable(true);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setText("Listado por Precio");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("Entre $");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText("y");

        jtEntre1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jtEntre1.setForeground(new java.awt.Color(0, 51, 153));
        jtEntre1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jtEntre1KeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jtEntre1KeyReleased(evt);
            }
        });

        jtEntre2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jtEntre2.setForeground(new java.awt.Color(0, 51, 153));
        jtEntre2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jtEntre2KeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jtEntre2KeyReleased(evt);
            }
        });

        tablaProd.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tablaProd);

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/listado.png"))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(108, 108, 108)
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addComponent(jtEntre1, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel3)
                        .addGap(28, 28, 28)
                        .addComponent(jtEntre2, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 376, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(127, 127, 127)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 57, Short.MAX_VALUE)
                .addComponent(jLabel4)
                .addGap(50, 50, 50))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(43, 43, 43)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jtEntre1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtEntre2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 277, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jtEntre1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtEntre1KeyPressed
        // TODO add your handling code here:
//        
//        boolean hayElementos = false;
//        
//        borrarFilas();
//
//        
//        if (jtEntre1.getText().isEmpty()) {
//            hayElementos = true;
//            mostrarTodo();
//        } else if(validaReal(jtEntre1.getText())){
//         double buscar = Double.parseDouble(jtEntre1.getText());  
//         buscar1= buscar;
//            for (Producto prod : productos) {
//                if (prod.getPrecio()>buscar) {
//                    hayElementos = true;
//                    tablaProducto.addRow(new Object[]{prod.getCodigo(), prod.getDescripcion(), prod.getPrecio(), prod.getRubro().getNombre(), prod.getStock()});
//                }
//            }
//        }else{
//             JOptionPane.showMessageDialog(this, "Debe ingresar un número.","Precio incorrecto",JOptionPane.ERROR_MESSAGE);
//            jtEntre1.requestFocus();
//            return;
//        }
//        
//        if (!hayElementos) {
//            tablaProducto.addRow(new Object[]{"No hay elementos que coincidan con la busqueda"});
//        }
    }//GEN-LAST:event_jtEntre1KeyPressed

    private void jtEntre2KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtEntre2KeyPressed
        // TODO add your handling code here:
        
        
//        if(validaReal(jtEntre2.getText())){
//         double buscar2 = Double.parseDouble(jtEntre2.getText());
//         borrarFilas(); 
//          for (Producto prod : productos) {
//        if (prod.getPrecio() >= buscar1 && prod.getPrecio() <= buscar2) {
//            tablaProducto.addRow(new Object[]{prod.getCodigo(), prod.getDescripcion(), prod.getPrecio(), prod.getRubro().getNombre(), prod.getStock()});
//        }
//    }
//         
//        }else{
//            JOptionPane.showMessageDialog(this, "Debe ingresar un número.","Precio incorrecto",JOptionPane.ERROR_MESSAGE);
//            jtEntre1.requestFocus();
//            return;
//        }
//    

   
    }//GEN-LAST:event_jtEntre2KeyPressed

    private void jtEntre1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtEntre1KeyReleased
        // TODO add your handling code here:
         
        boolean hayElementos = false;
        
        borrarFilas();

        
        if (jtEntre1.getText().isEmpty()) {
            hayElementos = true;
            mostrarTodo();
        } else if(validaReal(jtEntre1.getText())){
         double buscar = Double.parseDouble(jtEntre1.getText());  
         buscar1= buscar;
            for (Producto prod : productos) {
                if (prod.getPrecio()>buscar) {
                    hayElementos = true;
                    tablaProducto.addRow(new Object[]{prod.getCodigo(), prod.getDescripcion(), prod.getPrecio(), prod.getRubro().getNombre(), prod.getStock()});
                }
            }
        }else{
             JOptionPane.showMessageDialog(this, "Debe ingresar un número.","Precio incorrecto",JOptionPane.ERROR_MESSAGE);
            jtEntre1.requestFocus();
            return;
        }
        
        if (!hayElementos) {
            tablaProducto.addRow(new Object[]{"No hay elementos que coincidan con la busqueda"});
        }
    }//GEN-LAST:event_jtEntre1KeyReleased

    private void jtEntre2KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtEntre2KeyReleased
        // TODO add your handling code here:
         if(validaReal(jtEntre2.getText())){
         double buscar2 = Double.parseDouble(jtEntre2.getText());
         borrarFilas(); 
          for (Producto prod : productos) {
        if (prod.getPrecio() >= buscar1 && prod.getPrecio() <= buscar2) {
            tablaProducto.addRow(new Object[]{prod.getCodigo(), prod.getDescripcion(), prod.getPrecio(), prod.getRubro().getNombre(), prod.getStock()});
        }
    }
         
        }else{
            JOptionPane.showMessageDialog(this, "Debe ingresar un número.","Precio incorrecto",JOptionPane.ERROR_MESSAGE);
            jtEntre1.requestFocus();
            return;
        }
    
    }//GEN-LAST:event_jtEntre2KeyReleased


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jtEntre1;
    private javax.swing.JTextField jtEntre2;
    private javax.swing.JTable tablaProd;

    // End of variables declaration//GEN-END:variables

 

    // End of variables declaration          
    

 private void borrarFilas() {
        int filas = tablaProducto.getRowCount();

        for (int i = filas - 1; i >= 0; i--) {
            tablaProducto.removeRow(i);
        }
    }

    
    private void mostrarTodo() {
        for (Producto prod : productos) {
            tablaProducto.addRow(new Object[]{prod.getCodigo(), prod.getDescripcion(), prod.getPrecio(), prod.getRubro().getNombre(), prod.getStock()});
        }
    }
    private boolean validaReal(String nro){
    Pattern patron=Pattern.compile("[-+]?[0-9]*\\.?[0-9]+$");
        Matcher m=patron.matcher(nro);
        return m.matches();
        
    }
}
