package Vistas;

import Entidades.Producto;
import java.util.TreeSet;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;


public class PorNombre extends javax.swing.JInternalFrame {
    DefaultTableModel tablaModelo= new DefaultTableModel();
    private TreeSet<Producto> productos;
    
    
    public PorNombre(TreeSet<Producto> productos){
        //Debería recibir por parámetro la lista de productos en el constructor.
        
        
        initComponents();
        this.productos=productos;

       
        //Carga de la cabecera de la tabla.
        String[]titulo=new String[]{ "Código", "Descripcion", "Precio","Rubro", "Stock"};
        tablaModelo.setColumnIdentifiers(titulo);
        tablaProd.setModel(tablaModelo);
        mostrarTodo();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaProd = new javax.swing.JTable();
        jtBuscarNombre = new javax.swing.JTextField();

        setClosable(true);
        setResizable(true);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setText("Listado de Productos por Nombre");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setText("Escriba los primeros caracteres:");

        tablaProd.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tablaProd);

        jtBuscarNombre.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jtBuscarNombreKeyReleased(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(57, 57, 57)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addComponent(jLabel4)
                        .addGap(18, 18, 18)
                        .addComponent(jtBuscarNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(62, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(16, 16, 16)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(18, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel4)
                    .addComponent(jtBuscarNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(398, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(134, 134, 134)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 277, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(86, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    //Evento de ESCRIBIR EN EL jtBuscarNombre
    private void jtBuscarNombreKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtBuscarNombreKeyReleased
        // TODO add your handling code here:
        String buscar=jtBuscarNombre.getText().toLowerCase();
        boolean hayElementos=false;
        
        borrarFilas();//Limpia la tabla para poder actualizarla correctamente.
        
        //Si el jtBuscarNombre está vacío, muestra la lista completa.
        if(jtBuscarNombre.getText().isEmpty()){
            hayElementos=true;
            mostrarTodo();        
        }else{//Si hay texto, busca coincidencia con la descripción del producto y lo muestra en la tabla
            for(Producto prod:productos){
                if(prod.getDescripcion().toLowerCase().startsWith(buscar)){
                    hayElementos=true;
                    tablaModelo.addRow(new Object[]{prod.getCodigo(),prod.getDescripcion(),prod.getPrecio(),prod.getRubro().getNombre(),prod.getStock()});
                }
            }
        }
        //Si no hubo coincidencias, avisa que con Mensaje.
        if(!hayElementos){
            tablaModelo.addRow(new Object[]{"No hay elementos que coincidan con la busqueda"});
        }
    }//GEN-LAST:event_jtBuscarNombreKeyReleased


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jtBuscarNombre;
    private javax.swing.JTable tablaProd;
    // End of variables declaration//GEN-END:variables
    
    
    //Borra todas las filas de la tabla.
    private void borrarFilas() {
        int filas=tablaModelo.getRowCount();
        
        for(int i=filas-1;i>=0;i--){
            tablaModelo.removeRow(i);
        }
    }

    //Muestre en la tabla todos los elementos de la lista de productos.
    private void mostrarTodo() {
        for(Producto prod:productos){
            tablaModelo.addRow(new Object[]{prod.getCodigo(),prod.getDescripcion(),prod.getPrecio(),prod.getRubro().getNombre(),prod.getStock()});
        }
    }
}
